name: Deploy to Cloudflare Pages

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test --silent
      - uses: cloudflare/pages-action
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: blocked
          directory: ./pages